version: '3'

services:
  php-fpm:
    build: .docker/php-fpm
    volumes:
      - ./app/:/var/www/project
      - .docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - .docker/php-fpm/opcache.ini:/usr/local/etc/php/opcache.ini
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_KEY=${APP_KEY:-base64:8}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database/${POSTGRES_DB:-app}?charset=utf8

  node:
    image: node:alpine
    working_dir: /usr/share/app
    command: "sh -c 'npm install -g npm@latest && npm install && npm run dev'"
    ports:
      - "5173:5173"
    volumes:
      - ./frontoffice/:/usr/share/app


  nginx:
    build: .docker/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./app/:/var/www/project
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - .docker/nginx/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
      - .docker/nginx/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data: {}
