name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

run-name: Tests
    
jobs: 
  ######################################################
  #                     FRONTEND                       #
  ######################################################
  lint_front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd frontoffice && npm ci
    - name: Lint
      run: cd frontoffice && npm run lint
  tests_front:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd frontoffice && npm ci
    - name: Install Playwright Browsers
      run: cd frontoffice && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd frontoffice && npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontoffice/playwright-report/
        retention-days: 30

  ######################################################
  #                     BACKEND                        #
  ######################################################
  lint_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
    - name: Create .env file
      run: cd app && cp .env.example .env  
    - name: Download dependencies
      run: cd app && composer install
    - name: Lint
      run: cd app && ./vendor/bin/phpcs --standard=PSR12 src/
  tests_backend:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-22.04', 'windows-2022' ]
        php: [ '8.2', '8.3' ]
        symfony: [ '7.0.*']
        exclude:
        - php: '8.0'
          symfony: '7.0.*'
        - php: '8.1'
          symfony: '7.0.*'  
    steps:
      - uses: actions/checkout@v4  
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex  
      - name: Create .env file
        run: cd app && cp .env.example .env  
      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v2
        with:
            working-directory: "app/"  
      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: cd app/ && ./vendor/bin/phpunit
