name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress install
        run: npm install cypress 
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./frontoffice
          install-command: 'npm install'
          start-command: 'npm run dev'