name: Symfony PHPUnit Tests

on:
  push: ~
  pull_request: ~

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-22.04', 'windows-2022' ]
        php: [ '8.2', '8.3' ]
        symfony: [ '7.0.*']
        exclude:
        - php: '8.0'
          symfony: '7.0.*'
        - php: '8.1'
          symfony: '7.0.*'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Create .env file
        run: cd app && cp .env.example .env

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v2
        with:
            working-directory: "app/"

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: cd app/ && ./vendor/bin/phpunit