name: Playwright Tests
on:
  push:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd frontoffice && npm ci
    - name: Install Playwright Browsers
      run: cd frontoffice && npx playwright install
    - name: Run Playwright tests
      run: cd frontoffice && npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
